// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClOe7yzoxiknKEd43NmpQtZ6lPmLSmoJQ',
    appId: '1:92720067679:web:4f9676e6f84cb3d57417ea',
    messagingSenderId: '92720067679',
    projectId: 'ondc-seller-app-prototype',
    authDomain: 'ondc-seller-app-prototype.firebaseapp.com',
    databaseURL: 'https://ondc-seller-app-prototype-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ondc-seller-app-prototype.appspot.com',
    measurementId: 'G-0Q2HRGX59J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFQKAZPQtqViA94C3ncWW6WjU4oRAMouw',
    appId: '1:92720067679:android:a996f89162e70d537417ea',
    messagingSenderId: '92720067679',
    projectId: 'ondc-seller-app-prototype',
    databaseURL: 'https://ondc-seller-app-prototype-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ondc-seller-app-prototype.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj1ftyLr2OI5jgO08aygNYcqxTKQrTvBw',
    appId: '1:92720067679:ios:52d4478b474b8c2c7417ea',
    messagingSenderId: '92720067679',
    projectId: 'ondc-seller-app-prototype',
    databaseURL: 'https://ondc-seller-app-prototype-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ondc-seller-app-prototype.appspot.com',
    iosBundleId: 'com.example.vyser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj1ftyLr2OI5jgO08aygNYcqxTKQrTvBw',
    appId: '1:92720067679:ios:5075ee11ca3f89a57417ea',
    messagingSenderId: '92720067679',
    projectId: 'ondc-seller-app-prototype',
    databaseURL: 'https://ondc-seller-app-prototype-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ondc-seller-app-prototype.appspot.com',
    iosBundleId: 'com.example.vyser.RunnerTests',
  );
}
